# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Project:
  fields:
    default: name, user, project_type, public
    form: name, user, project_type, public
  order_by: user_id
  relationships: repository, project_collaborators
  filters: user, public
  search: name
  application: wide

ProjectType:
  fields:
    default: name, description
    form: name, description, makefile_template, repository_template
  order_by:
  relationships:
  filters:
  search: name
  application: wide

Repository:
  fields:
    default: project, path, scm
    form: project, path, scm
  order_by:
  relationships: project
  filters:
  search:
  application: wide

User:
  fields:
    default: user_name, active, email
    form: user_name, active, email
  order_by:
  relationships: projects
  filters: active
  search: user_name, email
  application: wide

ProjectCollaborator:
  fields:
    default: user
    form: user, project
  order_by:
  relationships: project, user
  filters: project, user
  search:

