# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Project:
  fields:
    default: name, user, project_type, public, status
    form: name, user, project_type, public
    options:
      booleans:
        public: ['Public', 'Private']
  order_by: user_id
  relationships: repository, collaborators, constants
  filters: user, public
  search: name
  application: wIDE

ProjectType:
  fields:
    default: name, description
    form: name, description, binary_extension, makefile_template, repository_template
  order_by:
  relationships: constants
  filters:
  search: name, description
  application: wIDE

Repository:
  fields:
    default: project, path, scm
    form: project, path, scm
  order_by:
  relationships: project
  filters:
  search:
  application: wIDE

User:
  fields:
    default: user_name, active, email, created_at
    form: user_name, active, email, password, password_confirmation
    options:
      booleans:
        active: ['Active', 'Inactive']
  order_by:
  relationships: projects
  filters: active
  search: user_name, email
  application: wIDE

ProjectCollaborator:
  fields:
    default: user
    form: user, project
  order_by:
  relationships: project, user
  filters: project, user
  search:

Constant:
  fields:
    default: name, value
    form: name, value
  order_by:
  relationships: container
  filters:
  search:
