# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Project: create, read, update, delete
  ProjectType: create, read, update, delete
  Repository: create, read, update, delete
  User: create, read, update, delete
  ProjectCollaborator: all
  Constant: all
