defaults: &defaults
  web_server_host: 'wide.labi.fi.uba.ar'
  repo_server_base: 'http://hg.wide.labi.fi.uba.ar/'
  email_address: 'wide@wide.labi.fi.uba.ar'
  ace_themes:
    - ["TextMate", "ace/theme/textmate"]
    - ["Eclipse", "ace/theme/eclipse"]
    - ["Dawn", "ace/theme/dawn"]
    - ["idleFingers", "ace/theme/idle_fingers"]
    - ["Pastel on dark", "ace/theme/pastel_on_dark"]
    - ["Twilight", "ace/theme/twilight"]
  default_ace_theme: ace/theme/textmate
  repositories_base: "/home/wide/application/shared/repositories"
  compilation_base: <%= Rails.root.join('compiled') %>

development:
  <<: *defaults
  repositories_base: <%= Rails.root.join('public', 'repositories') %>
  compilation_base: <%= Rails.root.join('public', 'compiled') %>

test:
  <<: *defaults

production:
  <<: *defaults
